version: "3.8"
services:
  postgres-db:
    container_name: tutorial
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_PASSWORD: tutorial
      POSTGRES_DB: tutorial
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5436:5432"

volumes:
  postgresql_data:
    driver: local