spring:
  application:
    name: tutorial

  datasource:
    url: jdbc:postgresql://localhost:5436/tutorial
    driver-class-name: org.postgresql.Driver
    username: tutorial
    password: tutorial
  flyway:
    enabled: true
    locations: classpath:db/migration
    jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none
  server:
    port: 8080